// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contributions": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contributions" | "/contact" | "/blog" | "/blog/:slug";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/contributions" | "/contact" | "/blog" | "/blog/:slug";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/contributions.tsx": {
    id: "routes/contributions";
    page: "/contributions";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/blog._index.tsx": {
    id: "routes/blog._index";
    page: "/blog";
  };
  "routes/blog.$slug.tsx": {
    id: "routes/blog.$slug";
    page: "/blog/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/layout": typeof import("./src/routes/layout.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/contributions": typeof import("./src/routes/contributions.tsx");
  "routes/contact": typeof import("./src/routes/contact.tsx");
  "routes/blog._index": typeof import("./src/routes/blog._index.tsx");
  "routes/blog.$slug": typeof import("./src/routes/blog.$slug.tsx");
};